# Generated by Django 4.2.11 on 2024-04-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cars",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="购物车编号"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Codes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="二维码编号"
                    ),
                ),
                ("location", models.CharField(max_length=20, verbose_name="位置")),
            ],
        ),
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="商品编号"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="商品价格"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="商品名称")),
                ("count", models.IntegerField(verbose_name="商品数量")),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="商品折扣",
                    ),
                ),
                ("introduce", models.CharField(max_length=3000, verbose_name="商品介绍")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="用户编号"
                    ),
                ),
                ("phone_number", models.CharField(max_length=15, verbose_name="手机号")),
                ("password", models.CharField(max_length=100, verbose_name="密码")),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="余额"
                    ),
                ),
                ("picture", models.CharField(max_length=255, verbose_name="照片")),
                (
                    "identity",
                    models.SmallIntegerField(
                        choices=[(1, "用户"), (2, "管理员")], default=1, verbose_name="身份"
                    ),
                ),
            ],
        ),
    ]
