# Generated by Django 4.2.11 on 2024-04-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=32, verbose_name="用户名")),
                ("password", models.CharField(max_length=32, verbose_name="密码")),
                (
                    "identity",
                    models.SmallIntegerField(
                        choices=[(1, "管理员")], default=1, verbose_name="身份"
                    ),
                ),
            ],
        ),
    ]
