# Generated by Django 4.2.11 on 2024-04-10 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="identity",
        ),
    ]
