# Generated by Django 4.2.11 on 2024-04-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0004_cars_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="电子标签编号"
                    ),
                ),
                ("tag_id", models.CharField(max_length=64, verbose_name="电子标签号")),
                ("goods_id", models.IntegerField(verbose_name="商品id")),
            ],
        ),
    ]
