# Generated by Django 4.2.11 on 2024-04-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0006_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="codes",
            name="code_id",
            field=models.IntegerField(default=-1, verbose_name="二维码ID"),
        ),
        migrations.AlterField(
            model_name="codes",
            name="location",
            field=models.CharField(max_length=50, verbose_name="位置"),
        ),
    ]
